//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinara.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinara.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_is_Empty.
        /// </summary>
        internal static string ErrorKeyEmptyValue {
            get {
                return ResourceManager.GetString("ErrorKeyEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_users_in_note.
        /// </summary>
        internal static string ErrorKeyEmpyNote {
            get {
                return ResourceManager.GetString("ErrorKeyEmpyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_data_to_edit.
        /// </summary>
        internal static string ErrorKeyNoData {
            get {
                return ResourceManager.GetString("ErrorKeyNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No_not_deleted_users.
        /// </summary>
        internal static string ErrorKeyOnlyDeleteUsers {
            get {
                return ResourceManager.GetString("ErrorKeyOnlyDeleteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the_same_{0}.
        /// </summary>
        internal static string ErrorKeySameValue {
            get {
                return ResourceManager.GetString("ErrorKeySameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operetion_with_deleted_users.
        /// </summary>
        internal static string ErrorKeyUseDeletedUsers {
            get {
                return ResourceManager.GetString("ErrorKeyUseDeletedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_not_found.
        /// </summary>
        internal static string ErrorKeyUserNotFound {
            get {
                return ResourceManager.GetString("ErrorKeyUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users in note.
        /// </summary>
        internal static string ErrorMessageEmptyNote {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Empty.
        /// </summary>
        internal static string ErrorMessageEmptyValue {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to edit.
        /// </summary>
        internal static string ErrorMessageNoData {
            get {
                return ResourceManager.GetString("ErrorMessageNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with {0} = {1} once exists.
        /// </summary>
        internal static string ErrorMessageSameDeletedValue {
            get {
                return ResourceManager.GetString("ErrorMessageSameDeletedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with {0} = {1} already exists.
        /// </summary>
        internal static string ErrorMessageSameValue {
            get {
                return ResourceManager.GetString("ErrorMessageSameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view deleted users.
        /// </summary>
        internal static string ErrorMessageSecurityError {
            get {
                return ResourceManager.GetString("ErrorMessageSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with {0} = {1} is not found.
        /// </summary>
        internal static string ErrorMessageUserNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageUserNotFound", resourceCulture);
            }
        }
    }
}
